### ISSUE TITLE
Could not complete the operation 'Upgrade the 'invidious' app'.

### ISSUE THREAD

**Issue by ctarx** [YunoHost-Apps/invidious_ynh#110]
### Describe the bug

Upgrade the 'invidious' app failed

### Context

- Hardware: Old computer
- YunoHost version: 11.0.11 (stable)

- `Invidious (invidious) from 23.01.06~ynh1 to 23.01.29~ynh1`

### Steps to reproduce

Upgrade application in a webadmin or via SSH

### Expected behavior

Upgrading

### Logs
https://paste.yunohost.org/raw/damizipisu

**Comment by tio-trom** [comment]
This is a duplicate of https://github.com/YunoHost-Apps/invidious_ynh/issues/109

**Comment by isAAAc** [comment]
### Describe the bug
upgrade  Invidious (invidious) from 23.01.06~ynh1 to 23.01.29~ynh1  is failing (in cli mode)


### Context

- Hardware: *VPS*
- Yunohost version:
```
root@krashboyz:~# yunohost -v
yunohost: 
  repo: stable
  version: 11.0.11
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.11.1
```
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

- Using, or trying to install package version/branch:    23.01.29~ynh1
- If upgrading, current package version: *23.01.06~ynh1*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    # yunohost app upgrade invidious
    ```

### Expected behavior

expected upgrade to the last stable version of invidious...

### Logs

https://paste.yunohost.org/raw/sutufetigo
