### ISSUE TITLE
upgrade, restoration and new install are failing since this morning (there was a crystal update this morning as far i can remember)

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/invidious_ynh#149]
This morning, after crystal upgrade, invidious can't upgrade and is auto-removed.
I can't retore it, nor reinstall.

(i link of issue with chatonsinfos_ynh, because i first believed the root-cause was chatonsinfos because of some messages in the prompt-return https://github.com/YunoHost-Apps/chatonsinfos_ynh/issues/6 )

### Context

- Hardware: VPS
```
root@krashboyz:/var/www# yunohost  --version
yunohost: 
  repo: stable
  version: 11.2.9.1
yunohost-admin: 
  repo: stable
  version: 11.2.4
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
 ``` 

- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
-  YNH_APP_CURRENT_VERSION: `23.12.18~ynh1`
- tried to upgrade into: `23.12.18~ynh2`

### Logs

upgrade ko: https://paste.yunohost.org/raw/okuqagagiy
restoration ko

i tried a workaround removing chatonsinfos and then trying to restore invidous, but it fails too :/
https://paste.yunohost.org/raw/kumiyekowa

reinstall ko: https://paste.yunohost.org/raw/wujibukebe

i tried to purge crystal , but same issue if i try to reinstall.

Thx for your help ;)
