### ISSUE TITLE
Misconfiguration of the RSS

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/invidious_ynh#43]
I've talked to the invidious developers about our instance that uses this ynh package and we realized ours has a misconfigured RSS which makes it not work properly with many RSS readers. Namely, the RSS links are relative:

```
<title>A boring bike ride through a busy &amp; bustling NYC</title>
    <link rel="alternate" href="/watch?v=KrkUiwfWToY"/>
    <author>
      <name>Louis Rossmann</name>
      <uri>/channel/UCl2mFZoRqjw_ELax4Yisf6w</uri>
    </author>
    <content type="xhtml">
      <div xmlns="http://www.w3.org/1999/xhtml">
        <a href="/watch?v=KrkUiwfWToY">
          <img src="/vi/KrkUiwfWToY/mqdefault.jpg"/>
        </a>
```

img src="/vi/KrkUiwfWToY/mqdefault.jpg" should be img src="https://ytb.trom.tf//vi/KrkUiwfWToY/mqdefault.jpg" for our instance.

Can you please fix this?

**Comment by ericgaspar** [comment]
Should be fixed with #45. Can you confirm?

**Comment by tio-trom** [comment]
Yes the issue is fixed. Thanks!

**Comment by tio-trom** [comment]
Here's a bug. After each URL there is a :300 . Like https://ytb.trom.tf:3000/watch?v=8HEfIJlcFbs

**Comment by ericgaspar** [comment]
Can you try to remove one of the port settings in `/var/www/invidious/config/config.yml`
I don't know if it is line `65` or line `79` that is causing the bug... (restart systemd for the change to be effective)

**Comment by tio-trom** [comment]
Removed both, one by one. Restarted the server twice. No difference.

**Comment by ericgaspar** [comment]
- is the RSS link working with this adresse: https://ytb.trom.tf:3000/watch?v=8HEfIJlcFbs?

**Comment by tio-trom** [comment]
The RSS feed still has the 3000 in the url. Check https://ytb.trom.tf/channel/UCBJycsmduvYEL83R_U4JriQ - I tested it by removing those lines you said one by one. Remove one, restart server. Check Invidious.

**Comment by tio-trom** [comment]
I even disabled proxy in config to see if it makes any difference. None

**Comment by ericgaspar** [comment]
> The RSS feed still has the 3000 in the url.

My point is: having this port on the URL could be the expected behaviour when going through a proxy.
I am able to have a working RSS feed from Invidious. (with the port in the adress)
Is your RSS feed working or not?

**Comment by tio-trom** [comment]
No it does not work.

```
---
channel_threads: 1
feed_threads: 1
output: invidious.log
log_level: info
decrypt_polling: true
full_refresh: false
https_only: true
domain: ytb.trom.tf
use_pubsub_feeds: false
popular_enabled: true
captcha_enabled: true
login_enabled: false
registration_enabled: false
statistics_enabled: true
admins: []
default_user_preferences:
  annotations: false
  annotations_subscribed: false
  autoplay: false
  captions:
  - ""
  - ""
  - ""
  comments:
  - youtube
  - reddit
  continue: false
  continue_autoplay: true
  dark_mode: "true"
  latest_only: false
  listen: false
  local: false
  locale: en-US
  max_results: 40
  notifications_only: false
  player_style: invidious
  quality: dash
  quality_dash: auto
  default_home: Popular
  feed_menu:
  - Popular
  - Trending
  - Subscriptions
  - Playlists
  automatic_instance_redirect: false
  related_videos: true
  sort: published
  speed: 1.0
  thin_mode: false
  unseen_only: false
  video_loop: false
  extend_desc: false
  volume: 100
  vr_mode: true
  show_nick: true
dmca_content: []
check_tables: false
cache_annotations: false
hsts: true
disable_proxy: false
force_resolve: ipv6
port: 3000
host_binding: 0.0.0.0
pool_size: 100
use_quic: true


```
